name: Fly Deploy
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group-${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Deploy to production app (main branch)
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: flyctl deploy --remote-only --app brokerageproject --dockerfile cmd/server/Dockerfile.prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Deploy to dev app (dev branch)
      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        run: flyctl deploy --remote-only --app brokerageproject-dev --dockerfile cmd/server/Dockerfile.prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
